export const Database = [
  {
    name: "Justin (Gary) Adkins",
    hireDate: [2021, 8, 11],
    hoursUsed: 0,
    location: "AR Jacksonville",
    position: "Assistant Manager",
  },
  {
    name: "River Allbritton",
    hireDate: [2021, 8, 23],
    hoursUsed: 0,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Nicholas (Nick) Ammons",
    hireDate: [2021, 7, 12],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Associate",
  },
  {
    name: "Evan Atkinson",
    hireDate: [2021, 8, 30],
    hoursUsed: 0,
    location: "VW Bryant",
    position: "Associate",
  },
  {
    name: "Ricki Boas",
    hireDate: [2021, 6, 29],
    hoursUsed: 0,
    location: "VW Sherwood",
    position: "Associate",
  },
  {
    name: "Caleb Borders",
    hireDate: [2021, 10, 4],
    hoursUsed: 0,
    location: "VW North LR",
    position: "Associate",
  },
  {
    name: "John Brewster",
    hireDate: [2021, 5, 10],
    hoursUsed: 0,
    location: "VW Bryant",
    position: "Associate",
  },
  {
    name: "Greg Burton",
    hireDate: [2017, 8, 14],
    hoursUsed: 0,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Ra'Shawn Canada",
    hireDate: [2021, 8, 25],
    hoursUsed: 0,
    location: "AR Maumelle",
    position: "Associate",
  },
  {
    name: "Brandon Chamblee",
    hireDate: [2021, 11, 8],
    hoursUsed: 0,
    location: "AR Jacksonville",
    position: "Associate",
  },
  {
    name: "Colton Childers",
    hireDate: [2021, 5, 11],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Associate",
  },
  {
    name: "Myles Clark",
    hireDate: [2021, 4, 19],
    hoursUsed: 0,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Chase Cook",
    hireDate: [2020, 6, 25],
    hoursUsed: 0,
    location: "VW Arkadelphia",
    position: "Manager",
  },
  {
    name: "Natasha Crawford",
    hireDate: [2018, 8, 13],
    hoursUsed: 40,
    location: "VW HS Albert Pike",
    position: "Manager",
  },
  {
    name: "Joseph Derossitt",
    hireDate: [2020, 12, 3],
    hoursUsed: 0,
    location: "VW HS Central Ave",
    position: "Assistant Manager",
  },
  {
    name: "Colten Eastworth",
    hireDate: [2021, 5, 11],
    hoursUsed: 0,
    location: "VW Rodney Parham",
    position: "Associate",
  },
  {
    name: "Zach Ehemann",
    hireDate: [2021, 11, 2],
    hoursUsed: 0,
    location: "AR Sherwood",
    position: "Associate",
  },
  {
    name: "Jaren Evans",
    hireDate: [2018, 12, 16],
    hoursUsed: 107,
    location: "VW Benton",
    position: "Manager",
  },
  {
    name: "Samantha Flowers",
    hireDate: [2021, 9, 25],
    hoursUsed: 0,
    location: "VW Texarkana",
    position: "Associate",
  },
  {
    name: "James Freeze",
    hireDate: [2016, 6, 15],
    hoursUsed: 56,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Kelcye Fry",
    hireDate: [2021, 5, 29],
    hoursUsed: 0,
    location: "VW Arkadelphia",
    position: "Assistant Manager",
  },
  {
    name: "Reece (Benjamin) Frye",
    hireDate: [2021, 3, 29],
    hoursUsed: 0,
    location: "VW HS Albert Pike",
    position: "Associate",
  },
  {
    name: "Austin Gilbert",
    hireDate: [2021, 7, 8],
    hoursUsed: 0,
    location: "VW HS Central Ave",
    position: "Associate",
  },
  {
    name: "Leif Gregan",
    hireDate: [2020, 9, 14],
    hoursUsed: 0,
    extraHours: 24,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Nathanael Hardister",
    hireDate: [2017, 5, 23],
    hoursUsed: 80,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Garrett Hatzell",
    hireDate: [2021, 9, 6],
    hoursUsed: 0,
    location: "AR University",
    position: "Associate",
  },
  {
    name: "Ethan Holland",
    hireDate: [2020, 3, 17],
    hoursUsed: 40,
    location: "VW North LR",
    position: "Manager",
  },
  {
    name: "Kevin Holmes",
    hireDate: [2021, 1, 6],
    hoursUsed: 30,
    location: "VW North LR",
    position: "Associate",
  },
  {
    name: "Paige Boozer (Holmes)",
    hireDate: [2021, 3, 5],
    hoursUsed: 30,
    extraHours: 10,
    location: "AR University",
    position: "Associate",
  },
  {
    name: "Damon Hoover",
    hireDate: [2021, 11, 1],
    hoursUsed: 0,
    location: "AR Sherwood",
    position: "Associate",
  },
  {
    name: "Brett Hula",
    hireDate: [2021, 6, 5],
    hoursUsed: 0,
    location: "AR Maumelle",
    position: "Assistant Manager",
  },
  {
    name: "Jonathan Janssen",
    hireDate: [2021, 7, 26],
    hoursUsed: 0,
    location: "AR Maumelle",
    position: "Associate",
  },
  {
    name: "Corbin Jenkins",
    hireDate: [2018, 1, 11],
    hoursUsed: 66,
    location: "AR Maumelle",
    position: "Manager",
  },
  {
    name: "Josh Jones",
    hireDate: [2021, 5, 3],
    hoursUsed: 0,
    location: "VW HS Central Ave",
    position: "Associate",
  },
  {
    name: "Terry Julian",
    hireDate: [2018, 10, 8],
    hoursUsed: 45,
    location: "VW Rodney Parham",
    position: "Manager",
  },
  {
    name: "Chris Kelley",
    hireDate: [2020, 3, 23],
    hoursUsed: 0,
    location: "VW/AR Chenal",
    position: "Manager",
  },
  {
    name: "Horace Kelley",
    hireDate: [2021, 7, 14],
    hoursUsed: 0,
    location: "VW Rodney Parham",
    position: "Associate",
  },
  {
    name: "Maya Kewak",
    hireDate: [2021, 10, 13],
    hoursUsed: 0,
    location: "VW HS Albert Pike",
    position: "Associate",
  },
  {
    name: "Tony Kifer",
    hireDate: [2021, 6, 24],
    hoursUsed: 0,
    location: "AR Otter Creek",
    position: "Assistant Manager",
  },
  {
    name: "Lauren Forthman",
    hireDate: [2021, 9, 1],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Associate",
  },
  {
    name: "Justin Lee",
    hireDate: [2021, 9, 18],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Associate",
  },
  {
    name: "David Lenderman",
    hireDate: [2018, 1, 11],
    hoursUsed: 0,
    location: "AR Otter Creek",
    position: "Manager",
  },
  {
    name: "Levyn Lewis",
    hireDate: [2021, 3, 8],
    hoursUsed: 0,
    location: "AR Otter Creek",
    position: "Associate",
  },
  {
    name: "Joseph Mapili",
    hireDate: [2021, 3, 1],
    hoursUsed: 0,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Micheal Martin",
    hireDate: [2019, 11, 19],
    hoursUsed: 0,
    location: "VW North LR",
    position: "Associate",
  },
  {
    name: "Cody Morrison",
    hireDate: [2021, 6, 8],
    hoursUsed: 0,
    location: "VW HS Albert Pike",
    position: "Associate",
  },
  {
    name: "Jay Myles",
    hireDate: [2020, 7, 20],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Assistant Manager",
  },

  {
    name: "Jack Newton",
    hireDate: [2018, 1, 11],
    hoursUsed: 0,
    location: "AR University",
    position: "Manager",
  },
  {
    name: "Tyler Oswald",
    hireDate: [2016, 7, 26],
    hoursUsed: 64,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Adam Reed",
    hireDate: [2020, 11, 30],
    hoursUsed: 0,
    location: "VW Rodney Parham",
    position: "Assistant Manager",
  },
  {
    name: "Isaac Rivera",
    hireDate: [2017, 8, 14],
    hoursUsed: 48,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Alejandro Robles",
    hireDate: [2020, 11, 23],
    hoursUsed: 8,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Nick Rodriguez",
    hireDate: [2020, 6, 8],
    hoursUsed: 0,
    location: "VW North LR",
    position: "Assistant Manager",
  },
  {
    name: "David Rose",
    hireDate: [2019, 12, 21],
    hoursUsed: 0,
    location: "VW Sherwood",
    position: "Manager",
  },
  {
    name: "Adam Russell",
    hireDate: [2018, 5, 7],
    hoursUsed: 48,
    location: "VW Bryant",
    position: "Manager",
  },
  {
    name: "Thadeus Samuelson",
    hireDate: [2020, 12, 17],
    hoursUsed: 8,
    location: "Warehouse",
    position: "Associate",
  },
  {
    name: "Simon Sharp",
    hireDate: [2020, 2, 15],
    hoursUsed: 0,
    location: "VW HS Albert Pike",
    position: "Assistant Manager",
  },
  {
    name: "Clayton Simpkins",
    hireDate: [2019, 3, 11],
    hoursUsed: 40,
    location: "VW Bryant",
    position: "Assistant Manager",
  },
  {
    name: "Ethan Smith",
    hireDate: [2021, 3, 8],
    hoursUsed: 0,
    location: "AR University",
    position: "Associate",
  },
  {
    name: "Rolland Strong",
    hireDate: [2021, 9, 6],
    hoursUsed: 0,
    location: "VW Bryant",
    position: "Associate",
  },
  {
    name: "Andrew Thompson",
    hireDate: [2021, 7, 27],
    hoursUsed: 0,
    location: "AR Jacksonville",
    position: "Associate",
  },
  {
    name: "Trevor Torgerson",
    hireDate: [2021, 5, 5],
    hoursUsed: 0,
    location: "VW Texarkana",
    position: "Manager",
  },
  {
    name: "Amy Ward",
    hireDate: [2021, 2, 19],
    hoursUsed: 0,
    location: "VW Benton",
    position: "Associate",
  },
  {
    name: "Thomas Ward",
    hireDate: [2021, 4, 4],
    hoursUsed: 0,
    location: "VW Rodney Parham",
    position: "Associate",
  },
  {
    name: "Jonathon Warner",
    hireDate: [2021, 3, 6],
    hoursUsed: 0,
    location: "AR University",
    position: "Assistant Manager",
  },
  {
    name: "Patrick Williams",
    hireDate: [2021, 8, 31],
    hoursUsed: 0,
    location: "VW HS Albert Pike",
    position: "Associate",
  },
  {
    name: "Seth Willis",
    hireDate: [2019, 11, 11],
    hoursUsed: 0,
    location: "AR University",
    position: "Associate",
  },
  {
    name: "Brandon Willman",
    hireDate: [2020, 5, 4],
    hoursUsed: 0,
    location: "VW/AR Chenal",
    position: "Assistant Manager",
  },
  {
    name: "Alex Wools",
    hireDate: [2019, 10, 14],
    hoursUsed: 0,
    location: "AR Jacksonville",
    position: "Manager",
  },
  {
    name: "Richard Wyllia",
    hireDate: [2021, 10, 11],
    hoursUsed: 0,
    location: "AR Otter Creek",
    position: "Associate",
  },
]
